version: "3"

vars:
  DIST_DIR: ./dist
  BUILD_DATE:
    sh: date -u +.b%y%m%d-%H%M%S
  LD_FLAGS: -s -w -X main.buildDateVersion={{.BUILD_DATE}}

tasks:
  # --------------------------------------------------------------------------
  # internal tasks
  # --------------------------------------------------------------------------
  build:
    internal: true
    cmds:
      - go build -ldflags "{{.LD_FLAGS}}" -buildvcs=false -o {{.DIST_DIR}}/{{.APP}} ./cmd/{{.APP}}
    env:
      CGO_ENABLED: 0
    requires:
      vars: [APP]

  build-windows-amd64:
    internal: true
    cmds:
      - go build -ldflags "{{.LD_FLAGS}}" -buildvcs=false -o {{.DIST_DIR}}/{{.APP}}-windows-amd64.exe ./cmd/{{.APP}}
    env:
      CGO_ENABLED: 0
      GOOS: windows
      GOARCH: amd64
    requires:
      vars: [APP]

  build-darwin-arm64:
    internal: true
    cmds:
      - go build -ldflags "{{.LD_FLAGS}}" -buildvcs=false -o {{.DIST_DIR}}/{{.APP}}-darwin-arm64 ./cmd/{{.APP}}
    env:
      CGO_ENABLED: 0
      GOOS: darwin
      GOARCH: arm64
    requires:
      vars: [APP]

  build-linux-amd64:
    internal: true
    cmds:
      - go build -ldflags "{{.LD_FLAGS}}" -buildvcs=false -o {{.DIST_DIR}}/{{.APP}}-linux-amd64 ./cmd/{{.APP}}
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    requires:
      vars: [APP]

  # --------------------------------------------------------------------------
  # build all
  # --------------------------------------------------------------------------

  clean:
    cmds:
      - rm -rf {{.DIST_DIR}}

  build-all:
    cmds:
      - task: build-protogen-all
      - task: build-protogen-ts-all

  # --------------------------------------------------------------------------
  # dependencies
  # --------------------------------------------------------------------------

  update-all:
    cmds:
      - go get -u ./...

  # --------------------------------------------------------------------------
  # protogen
  # --------------------------------------------------------------------------

  build-protogen:
    cmds:
      - task: build
        vars:
          APP: protogen

  build-protogen-all:
    cmds:
      - task: build-windows-amd64
        vars:
          APP: protogen
      - task: build-darwin-arm64
        vars:
          APP: protogen
      - task: build-linux-amd64
        vars:
          APP: protogen

  run-protogen:
    cmds:
      - go run cmd/protogen/*.go {{.CLI_ARGS}}

  # --------------------------------------------------------------------------
  # protogen-ts
  # --------------------------------------------------------------------------

  build-protogen-ts:
    cmds:
      - task: build
        vars:
          APP: protogen-ts

  build-protogen-ts-all:
    cmds:
      - task: build-windows-amd64
        vars:
          APP: protogen-ts
      - task: build-darwin-arm64
        vars:
          APP: protogen-ts
      - task: build-linux-amd64
        vars:
          APP: protogen-ts

  run-protogen-ts:
    cmds:
      - go run cmd/protogen-ts/*.go {{.CLI_ARGS}}

  run-protogen-ts-test:
    cmds:
      - go run cmd/protogen-ts/*.go
        --proto test/proto/constants.proto
        --const test/output/constants.ts
        --msg test/output/constantMessages.ts
        --rename Error=ErrorType
